name: passenger_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  common:
    path: ../packages/common
  country_code_picker: ^2.0.2
  dio: ^4.0.6
  firebase_core: ^1.15.0
  firebase_messaging: ^11.2.14
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.4.1
  flutter_localizations:
    sdk: flutter
  flutter_polyline_points: ^1.0.0
  flutter_rating_bar: ^4.0.0
  flutter_riverpod: ^1.0.3
  geocoding: ^2.0.2
  geolocator: ^8.2.0
  google_maps_flutter: ^2.1.3
  tuple: ^2.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
